### ISSUE TITLE
Not able to set up

### ISSUE THREAD

**Issue by kabzo** [Avature/lxd-image-server#1]
Hello, this project looks very promising. However, I am not able to set it up. I was able to install it correctly and run `lxd-image-server init` without any errors. 

On my host,  I did add the host to remote. Result of `lxc remote list`
```test-lxd-image-server | https://10.127.46.100                    | simplestreams | none        | YES    | NO```

However, when I run 
```lxc image copy some-created-image test-lxd-image-server:```
I am getting
```Error: The remote isn't a private LXD server```

Do you have maybe more detailed explanation of how to set this project up? 
Thanks

**Comment by davidesba** [comment]
Hi,
The correct command to copy the image is:

```lxc image copy test-lxd-image-server:<image_hash> local:```

In order to check the images stored in the server you can use:

```lxc image list test-lxd-image-server:```

I will add this example to the documentation

**Comment by kabzo** [comment]
thanks! But how do I get the images to the server? The example you provided `lxc image copy test-lxd-image-server:<image_hash> local:` does a copy from `test-lxd-image-server` to local machine. How about the other way around? When I run `lxc image copy image-name test-lxd-image-server:some-container` I am still getting the same error

Runig this  `lxc image list test-lxd-image-server:` results in
```Error: Get https://localhost/streams/v1/index.json: EOF```
I assume because there are no images

**Comment by davidesba** [comment]
Images cannot be uploaded using lxc command. In order to upload an image into the server you have to create a directory with the image files (using scp or similar) according to this format:

```
- /var/www                                         # document root
        `- simplestreams
           |- images                               # images folder
           |  `- iats                              # environment
           |     `- xenial                         # release
           |        `- amd64                       # architecture
           |           `- default                  # box type
           |              `- 20180716_12:00        # version 1
           |                 |- lxd.tar.xz         # index and templates
           |                 `- rootfs.squashfs    # rootfs of container
           `- streams
              `- v1
                 |- index.json                     # index of products
                 `- images.json                    # info with versions of products
```

**Comment by kabzo** [comment]
ah I see, thanks. And how do you generate the `tar.xz` and `rootfs.squashfs` files? Because the `lxc image export` generates different files.

**Comment by davidesba** [comment]
To export a lxd image:
```
mkdir new_image
lxc image export <image_hash> new_image
```
This will create the .tar.xz and .squashfs files

After that you just need to rename them to lxd.tar.xz and rootfs.squashfs and upload them to the server

**Comment by kabzo** [comment]
Unfortunately that is not the case for me.  I am running lxc 3.14
I get:
```
juraj@host:~/Downloads$ mkdir test
juraj@host:~/Downloads$ lxc image export ce240e9b8b8d test
Image exported successfully!           
juraj@host:~/Downloads$ ls test/
ce240e9b8b8ddc95ac0abed532ba90b5601bc61b23196d2dfff149707de27003.tar.gz

```

any idea?

**Comment by davidesba** [comment]
In version 3.0.3 is working fine, I will check later with a new version of lxd

**Comment by davidesba** [comment]
With version 3.14, you don't need to create the directory (this example is done using ubuntu disco official image):
```
lxc image export f2e12e4ef9ea

ls
f2e12e4ef9eaad2c96de9ae72a3aad4bf4f9bcf031ecf1baa1e5a90ec1440092.squashfs
meta-f2e12e4ef9eaad2c96de9ae72a3aad4bf4f9bcf031ecf1baa1e5a90ec1440092.tar.xz

**Comment by kabzo** [comment]
This is interesting. For me:
```
lxc image export 14933a8abb69
ls
14933a8abb69b17f7112fc832bcd03e7b88508346861f511eb31376e0dc407d6.tar.gz```
I am running Ubuntu 18 installed from snap

**Comment by davidesba** [comment]
> This is interesting. For me:
> 
> ```
> lxc image export 14933a8abb69
> ls
> 14933a8abb69b17f7112fc832bcd03e7b88508346861f511eb31376e0dc407d6.tar.gz```
> I am running Ubuntu 18 installed from snap
> ```

And what is the output for you when using a directory?

**Comment by kabzo** [comment]
> > This is interesting. For me:
> > ```
> > lxc image export 14933a8abb69
> > ls
> > 14933a8abb69b17f7112fc832bcd03e7b88508346861f511eb31376e0dc407d6.tar.gz```
> > I am running Ubuntu 18 installed from snap
> > ```
> 
> And what is the output for you when using a directory?

The one in https://github.com/Avature/lxd-image-server/issues/1#issuecomment-510105855

**Comment by davidesba** [comment]
It seems lxd is putting everything inside the tgz if the source is a container. In this case, I guess you need to extract the files and put the rootfs dir in a squash file and the rest of the files in a tar.xz

**Comment by cr1st1p** [comment]
@davidesba can you please let us know what's with the following snippet from the README file?
```
lxc image copy bionic-vim <url>
```
It leaves the impression this software CAN have images uploaded directly.
If that is not the case, like the posts from here seem to suggest, I'm not sure how people would use this software without additional ones, and I would recommend
to remove that snippet from the readme file, and  clearly document upfront that you need something else to upload images.
Note: I reached this project because I want to be able to do BOTH read and write, easily.

Thank you!

**Comment by cduelo** [comment]
Thanks! I have add a url to the lxc site.
