### ISSUE TITLE
Debian packages no more available for Xenial

### ISSUE THREAD

**Issue by vrubiolo** [Avature/lxd-image-server#10]
Hi there,

We are looking into deploying `lxd-image-server` on our infrastructure and are following the associated README.

We stumble however because the Debian packages do not seem to be available anymore:
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

vagrant@ubuntu-xenial:~$ sudo apt-get install lxd-image-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lxd-image-server
```

This matches a [package search for Ubuntu](https://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=lxd-image-server) which does not return anything

Are the prebuilt packages still supported?

Thanks much for your assistance here!

**Comment by vrubiolo** [comment]
Hi there, any news on this issue? Thanks.

**Comment by cduelo** [comment]
Thanks for your comment @vrubiolo , we are not maintaining the debian packages.

You can build your own package with https://github.com/Avature/lxd-image-server#building-the-package-in-a-docker-container This is an example, you can use to build your own package in the debian based distribution you like.

**Comment by vrubiolo** [comment]
@carlosduelo : thanks for the feedback.

When I saw `dpkg -i lxd-image-server_0.0.1~xenial_all.deb` in the documentation, I assumed the package came from the standard Debian repos (or at least a PPA). 

It looks like I might have been wrong. So when the doc says at the installation part, `From debian package (recommended)`, this actually meant the Debian package built via the Dockerfile infrastructure at https://github.com/Avature/lxd-image-server#building-the-package-in-a-docker-container, right?
