### ISSUE TITLE
Image server cache

### ISSUE THREAD

**Issue by mutech** [Avature/lxd-image-server#13]
I'm looking for an LXD image server that acts as cache for remote images with the sole purpose to reduce download times and save network bandwidth while retaining the capability to get updated images. It would be great if a search for images by criteria or name would be available, but that's not required.

I don't want to mirror the whole remote repository, neither do I need to publish images locally.

Can this server be set up to do that and/or are there better alternatives for this use case?

From reading the documentation here, I did not find an answer, searching for `caching lxd image server` and similar did not reveal any results. It's probably a trivial question/problem, sorry for the noise if I'm just too ignorant.

**Comment by murlock** [comment]
You could use a local proxy (squid for example) and configure it in LXC configuration:

```
lxc config set core.proxy_https http://username:password@<IP>:<port>/
```

Regards

**Comment by mutech** [comment]
Wouldn't I run into the usual https-proxy problems, such as the proxy not actually caching and just forwarding traffic?

**Comment by mutech** [comment]
Thanks @murlock
