### ISSUE TITLE
PATCH: allow logging on stdout/stderr

### ISSUE THREAD

**Issue by cr1st1p** [Avature/lxd-image-server#2]
I want to run the code inside docker, so output should be on console.
Attached - a patch to allow that.

[cli.py.patch.txt](https://github.com/Avature/lxd-image-server/files/4086589/cli.py.patch.txt)

**Comment by cduelo** [comment]
Hi, Can you please send pull request?
Thanks!

**Comment by cr1st1p** [comment]
see #3
