### ISSUE TITLE
Incorrect checkums and fields

### ISSUE THREAD

**Issue by cr1st1p** [Avature/lxd-image-server#5]
I tried putting content from one lxc image export's outcome.
It had 2 components, one seem to be the lxd.tar.xz and one the squashfs content.

After putting them under the lxd-image-server, ```lxc image list myremote:``` does not show them.

After digging, it looks like:
- combined_sha256 is a legacy field, there is a new name
- for this particular case, a *different* field needs to be set: combined_squashfs_sha256
- current code computing the combined checksum is bogus - it combines **whatever** files there are in the directory.

A link regarding the checksums, for example: https://bugs.launchpad.net/cloud-images/+bug/1577922

I'll probably write a fix for this too, since I need it...

**Comment by gartnera** [comment]
Thanks for the fix, this resolved https://github.com/lxc/lxd/issues/6798 for me.

**Comment by jvrsantacruz** [comment]
Hi @cr1st1p thanks for bringing this issue to us. We'll be reviewing this shortly and release a new version with the fix.

¿Could you send the patch as a Pull Request? 
That way your contribution will be part of the project.

Thank you!

**Comment by cr1st1p** [comment]
I'll prepare soon a PR,  with even more fixes and improvements than for this bug report.
On the other hand... you already have another PR from me, that has not seen any activity for like 9 days.

**Comment by cr1st1p** [comment]
See PR #6 - it contains other fixes and improvements as well.
